### ISSUE TITLE
Ability to accept an invite from a link

### ISSUE THREAD

**Issue by willbarrett** [speak/website#51] opened 2015-08-25 17:32 UTC
E.G. join an organization if you're an existing user. This is probably the beginnings of our account area. We'll need to make the user auth if they haven't already, so that's probably the biggest chunk of work.

**Comment by tommoor** [comment] 2015-08-25 18:12
What do we think is the advantage here? Sounds like a lot of duplication to moi. We could have a button to open the app on Mac, we store which client they are using so this would be relatively simple

**Comment by willbarrett** [comment] 2015-08-25 18:13
Referring question to @ericbieller

**Comment by ericbieller** [comment] 2015-08-25 18:29
Works for me as long as we have cross platform compat. One caveat is if they don't have the app installed. In either case, we'd still have the accept button in email, or maybe a launch button?

**Comment by willbarrett** [comment] 2015-08-25 18:33
It won't be cross-platform. Linux support is virtually impossible.

**Comment by tommoor** [comment] 2015-08-25 20:57
Right, but we can inject the launch button if we know they are using the Mac app.




Good point on a download link, I think it makes sense to get a note at the bottom with a link in asap for those that have an account but uninstalled the app

**Comment by tommoor** [comment] 2015-10-24 22:24
Dupe of #67

**Closed by tommoor** 2015-10-24 22:24 UTC
Labels: enhancement
